### ISSUE TITLE
Compatibility with Firedrake_20220411.0

### ISSUE THREAD

**Issue by jcallaham** [IvanYashchuk/firedrake-ts#17]
The tests are currently failing - looks like firedrakeproject/firedrake#1983 refactored `assemble.py`, including removing the `assemble_type` kwarg.

Initial function:
https://github.com/firedrakeproject/firedrake/blob/1e0f9ed8ed9e6ea1a627471730dda0bddb7fd1fa/firedrake/assemble.py#L134-L169

Current version:
https://github.com/firedrakeproject/firedrake/blob/a77a4996d61da8f8b5710589e1a754357a79886f/firedrake/assemble.py#L223-L284

This conflicts with things like the `assemble_residual` function in `firedrake_ts.solving_utils._TSContext`, which hardcodes `assemble_type` as an argument to `assemble`:
https://github.com/IvanYashchuk/firedrake-ts/blob/879935387e486870308101e6d1bd8f393c762bea/firedrake_ts/solving_utils.py#L189-L196.

**Comment by IvanYashchuk** [comment]
Hey Jared! Thanks a lot for filing an issue and submitting a fix!
I'll review the proposed changes later today.

**Comment by IvanYashchuk** [comment]
Fixed in https://github.com/IvanYashchuk/firedrake-ts/pull/18. Thanks a lot!

**Comment by jcallaham** [comment]
No problem.  This is a great package, by the way - thanks for keeping it going!
